name: S3 CI

on:
  workflow_dispatch:
    inputs:
      pages:
        description: 'Array of page numbers to process'
        required: true
        default: '[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]'

jobs:
  provide_pages_array:
    runs-on: ubuntu-latest

    steps:
      - id: set-matrix
        run: echo "::set-output name=matrix::${{ github.event.inputs.pages }}"
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}

  ci:
    needs: provide_pages_array
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        page: ${{ fromJson(needs.provide_pages_array.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run scraper
        env:
          S3_ENDPOINT: ${{ secrets.S3_ENDPOINT }}
          S3_ACCESS_KEY: ${{ secrets.S3_ACCESS_KEY }}
          S3_SECRET_KEY: ${{ secrets.S3_SECRET_KEY }}
          S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
          TAXON_ID: ${{ secrets.TAXON_ID }}
          PAGE: ${{ matrix.page }}
        run: |
          python scraper.py -t $TAXON_ID -s $PAGE --upload-to-s3 --one-page-only
