name: S3 CI

on:
  workflow_dispatch:
  push:

permissions:
  contents: read

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        page: [1, 2, 3]

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run scraper
      env:
        S3_ENDPOINT: ${{ secrets.S3_ENDPOINT }}
        S3_ACCESS_KEY: ${{ secrets.S3_ACCESS_KEY }}
        S3_SECRET_KEY: ${{ secrets.S3_SECRET_KEY }}
        S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
        TAXON_ID: ${{ secrets.TAXON_ID }}
        PAGE_NUMBER: ${{ matrix.page }}
      run: |
        python scraper.py -t $TAXON_ID -p $PAGE_NUMBER --upload-to-s3
